# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 670b5c7a2f0603899928e4c856411f7705b3e8aff1ed4e4aea3ca7ac2b3548a81d463c1ddb85130a875a35a973fd3f5e1cf76a07064666dbf1cd92247456314e

test:
  secret_key_base: 5751e3b4a04b0ef53db80847dd7f8289b01b84c44ff11124ef6c859b78c5e7a8ea7a1cb6b8b2879a44ebfc9fd2b9f3ea5fa022c7917f45f6afef3e5dcf0a18b4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
